<Project>
    <PropertyGroup>
        <Version>0.0.1</Version>

        <Authors>trev</Authors>
        <Copyright>Copyright (c) 2025 trev.app</Copyright>
		<Description>NativeAOT-based Unity mod loader for Il2CPP</Description>

        <LangVersion>Latest</LangVersion>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(RuntimeIdentifier.StartsWith(`linux-bionic`))' == 'true'">
        <RuntimeIdentifiers>linux-bionic-arm64</RuntimeIdentifiers>
        <RuntimeIdentifier>linux-bionic-arm64</RuntimeIdentifier>
        <PlatformTarget>arm64</PlatformTarget>
        <DefineConstants>$(DefineConstants);ANDROID</DefineConstants>
        <LibPrefix>lib</LibPrefix>
        <LibExt>.a</LibExt>
    </PropertyGroup>
</Project>
