<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<TomlynIsReflectionEnabledByDefault>true</TomlynIsReflectionEnabledByDefault>
  </PropertyGroup>

  <!-- forces constants while designing -->
  <PropertyGroup Condition="'$(DesignTimeBuild)' == 'true'">
	<DefineConstants>$(DefineConstants);ANDROID;WINDOWS</DefineConstants>
  </PropertyGroup>

  <!-- linux-bionic specific settings -->
  <Import Condition="'$(RuntimeIdentifier.StartsWith(`linux-bionic-`))' == 'true'" Project="BionicNativeAot.targets" />
  <Target Condition="'$(RuntimeIdentifier.StartsWith(`linux-bionic-`))' == 'true'" Name="RenameBinaryBionic" AfterTargets="Publish">
    <Move SourceFiles="$(PublishDir)/$(TargetName).so" DestinationFiles="$(PublishDir)/libmain.so" />
  </Target>

  <PropertyGroup Condition="'$(RuntimeIdentifier.StartsWith(`linux-bionic-`))' == 'true'">
	  <DefineConstants>$(DefineConstants);ANDROID</DefineConstants>
  </PropertyGroup>
	
  <!-- linux (including bionic) specific settings -->
  <PropertyGroup Condition="'$(RuntimeIdentifier.StartsWith(`linux-`))' == 'true'">
    <LinkStandardCPlusPlusLibrary>true</LinkStandardCPlusPlusLibrary>
  </PropertyGroup>
	
  <!-- Windows specific settings -->
  <PropertyGroup Condition="'$(RuntimeIdentifier.StartsWith(`win-`))' == 'true'">
	<DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
	<DllMainUseQueueUserApc>true</DllMainUseQueueUserApc>
  </PropertyGroup>

  <Target Condition="'$(RuntimeIdentifier.StartsWith(`win-`))' == 'true'" Name="RenameBinaryWindows" AfterTargets="Publish">
	  <Move SourceFiles="$(PublishDir)/$(TargetName).dll" DestinationFiles="$(PublishDir)/winhttp.dll" />
  </Target>

  <ItemGroup Condition="'$(RuntimeIdentifier.StartsWith(`win-`))' == 'true'">
	<LinkerArg Include="/DEF:exports.def" />
	<PackageReference Include="NativeDllMain" Version="1.0.0" />
  </ItemGroup>
	
  <!-- universal things -->

  <ItemGroup>
    <NativeLibrary Include="Deps/$(RuntimeIdentifier)/$(LibPrefix)dobby$(LibExt)" />
    <PackageReference Include="Tomlyn" Version="2.3.0" />
    <ProjectReference Include="..\reference\xarsu.Reference.csproj" />
  </ItemGroup>

</Project>
