using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace xarsu.HookGenerator;

[Generator]
public class HookGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methods = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "xarsu.Reference.Il2CppHookAttribute",
                predicate: (node, _) => node is MethodDeclarationSyntax,
                transform: (ctx, _) => GetHookInfo(ctx));

        context.RegisterSourceOutput(methods.Collect(), Generate);
    }

    private static HookInfo? GetHookInfo(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not IMethodSymbol method) return null;
        var attr = ctx.Attributes[0];

        // get the declaring type from the attribute
        if (attr.ConstructorArguments[0].Value is not INamedTypeSymbol declaringType) return null;
        string il2cppMethodName = attr.ConstructorArguments[1].Value?.ToString() ?? "";

        // find the matching method on the declaring type to get parameter info
        var il2cppMethod = declaringType.GetMembers(il2cppMethodName)
            .OfType<IMethodSymbol>()
            .FirstOrDefault();

        // figure out if instance method and what the instance type is
        bool isStatic = il2cppMethod?.IsStatic ?? true;
        string? instanceTypeName = isStatic ? null : declaringType.ToDisplayString();

        // build param list from the hook method's actual parameters
        // skip the first param if it matches the instance type (we'll convert it)
        var hookParams = method.Parameters.ToList();

        return new HookInfo(
            ContainingClass: method.ContainingType.ToDisplayString(),
            HookMethodName: method.Name,
            Parameters: method.Parameters.Select(p => (p.Type.ToDisplayString(), p.Name)).ToArray(),
            ReturnType: method.ReturnType.ToDisplayString(),
            Il2CppDeclaringType: declaringType.ToDisplayString(),
            Il2CppMethodName: il2cppMethodName,
            IsStatic: isStatic,
            InstanceTypeName: instanceTypeName
        );
    }

    private static void Generate(SourceProductionContext ctx, ImmutableArray<HookInfo?> hooks)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");

        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using xarsu.Reference;");
        sb.AppendLine();

        foreach (var group in hooks.Where(h => h != null).GroupBy(h => h!.ContainingClass))
        {
            string ns = GetNamespace(group.Key);
            string className = GetClassName(group.Key);

            sb.AppendLine($"namespace {ns} {{");
            sb.AppendLine($"partial class {className} {{");

            foreach (var hook in group)
            {
                string delegateName = $"{hook!.HookMethodName}_Delegate";
                string hookFieldName = $"{hook.HookMethodName}_Hook";
                string trampolineName = $"{hook.HookMethodName}_Original";

                // generate the raw delegate, always uses IntPtr for instance
                // since this is what Dobby gives us
                var rawParams = new List<string>();
                if (!hook.IsStatic)
                    rawParams.Add("System.IntPtr __instance");
                // add the rest of the params as IntPtr since we don't know the raw types
                // the hook method itself handles converting
                foreach (var (type, name) in hook.Parameters.Skip(hook.IsStatic ? 0 : 1))
                    rawParams.Add($"{type} {name}");

                string rawParamList = string.Join(", ", rawParams);

                var userFacingParams = new List<string>();
                if (!hook.IsStatic)
                    userFacingParams.Add($"{hook.InstanceTypeName} {hook.Parameters[0].Item2}");
                userFacingParams.AddRange(hook.Parameters.Skip(hook.IsStatic ? 0 : 1).Select(p => $"{p.Item1} {p.Item2}"));

                string userFacingParamList = string.Join(", ", userFacingParams);

                sb.AppendLine($"    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]");
                sb.AppendLine($"    public delegate {hook.ReturnType} {delegateName}({rawParamList});");
                sb.AppendLine();

                sb.AppendLine($"    public static xarsu.Reference.Il2CppHook<{delegateName}>? {hookFieldName};");
                sb.AppendLine();

                // trampoline wrapper that converts instance for the user
                sb.AppendLine($"    public static {hook.ReturnType} {trampolineName}({userFacingParamList}) {{");
                if (!hook.IsStatic)
                {
                    // convert typed instance back to IntPtr for the raw trampoline
                    List<string> trampolineArgs = [];
                    trampolineArgs.Add($"{hook.Parameters[0].Item2}?.Pointer.Value ?? System.IntPtr.Zero");
                    trampolineArgs.AddRange(hook.Parameters.Skip(1).Select(p => p.Item2));

                    string trampolineArgStr = string.Join(", ", trampolineArgs);
                    if (hook.ReturnType != "void")
                        sb.AppendLine($"        return {hookFieldName}?.Original?.Invoke({trampolineArgStr}) ?? default;");
                    else
                        sb.AppendLine($"        {hookFieldName}?.Original?.Invoke({trampolineArgStr});");
                }
                else
                {
                    var trampolineArgs = hook.Parameters.Select(p => p.Item2).ToList();
                    trampolineArgs.Add("System.IntPtr.Zero");
                    string trampolineArgStr = string.Join(", ", trampolineArgs);
                    if (hook.ReturnType != "void")
                        sb.AppendLine($"        return {hookFieldName}?.Original?.Invoke({trampolineArgStr}) ?? default;");
                    else
                        sb.AppendLine($"        {hookFieldName}?.Original?.Invoke({trampolineArgStr});");
                }
                sb.AppendLine($"    }}");
                sb.AppendLine();

                // the raw detour that Dobby calls, converts instance and calls user's method
                sb.AppendLine($"    private static {hook.ReturnType} {hook.HookMethodName}_Detour({rawParamList}) {{");
                if (!hook.IsStatic)
                {
                    sb.AppendLine($"        var __typedInstance = __instance.AsIl2CppOrNull<{hook.InstanceTypeName}>();");
                    sb.AppendLine($"        if (__typedInstance == null) throw new Exception(\"Failed to convert instance to {hook.InstanceTypeName}\");");
                    // build the call to the user's actual hook method
                    var callArgs = new List<string> { "__typedInstance" };
                    callArgs.AddRange(hook.Parameters.Skip(1).Select(p => p.Item2));
                    string callArgStr = string.Join(", ", callArgs);
                    if (hook.ReturnType != "void")
                        sb.AppendLine($"        return {hook.HookMethodName}({callArgStr});");
                    else
                        sb.AppendLine($"        {hook.HookMethodName}({callArgStr});");
                }
                else
                {
                    var callArgs = hook.Parameters.Select(p => p.Item2);
                    string callArgStr = string.Join(", ", callArgs);
                    if (hook.ReturnType != "void")
                        sb.AppendLine($"        return {hook.HookMethodName}({callArgStr});");
                    else
                        sb.AppendLine($"        {hook.HookMethodName}({callArgStr});");
                }
                sb.AppendLine($"    }}");
                sb.AppendLine();

                // install method
                sb.AppendLine($"    public static void Install_{hook.HookMethodName}() {{");
                sb.AppendLine($"        var __method = xarsu.Reference.IL2CPP.GetIl2CppMethodPointer(typeof({hook.Il2CppDeclaringType}).GetMethod(\"{hook.Il2CppMethodName}\"));");
                sb.AppendLine($"        {hookFieldName} = xarsu.Reference.Il2CppHook.Install<{delegateName}>(__method, {hook.HookMethodName}_Detour);");
                sb.AppendLine($"    }}");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine("}");
        }

        sb.AppendLine();
        sb.AppendLine("#nullable disable");

        ctx.AddSource("Hooks.g.cs", sb.ToString());
    }

    private static string GetNamespace(string fullName)
    {
        int last = fullName.LastIndexOf('.');
        return last >= 0 ? fullName[..last] : "global";
    }

    private static string GetClassName(string fullName)
    {
        int last = fullName.LastIndexOf('.');
        return last >= 0 ? fullName[(last + 1)..] : fullName;
    }

    record HookInfo(
        string ContainingClass,
        string HookMethodName,
        (string, string)[] Parameters,
        string ReturnType,
        string Il2CppDeclaringType,
        string Il2CppMethodName,
        bool IsStatic,
        string? InstanceTypeName);
}